name: CI with Playwright and Maven

on:
  push:
    branches: [ Task_2_Playwright ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
         working-directory: ./Task_2

    steps:
        
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Java (Maven)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Install Playwright browsers
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

      - name: Run Maven tests
        run: mvn test
